version: '3.3'

services:
  app:
    container_name: wallethawk-app
    build: "./app"
    ports:
      - "80:80"
    networks:
      - backend-api

  api-server:
    container_name: wallethawk-api
    build: "./api-server"
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - APP_PORT=80
      - DB_PORT=3306
      - DB_HOST=database
    networks:
      - backend-api
      - backend
    command: 'npm start'

  file-server:
    hostname: file
    container_name: wallethawk-file
    build: "./file-server"
    ports:
      - "8001"
    environment:
      - PORT=8001
      - API_PORT=8000
    networks:
      - backend
    command: 'npm start'

  sql-server:
    hostname: database
    container_name: wallethawk-db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=wallet-hawk
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql

networks:
  backend-api:
  backend:

volumes:
  db:
