export const locale = 'da-DK';
export const dateFormat = 'YYYY/MM/dd';
export const passwordMinimumLength = 8;
export const passwordMaximumLength = 50;
export const passwordRegExp = /^(?=.{8,}$)(?=.*[\w])(?=.*[\W,_])(?!.*\s).*$/;
export const emailMinimumLength = 1;
export const emailMaximumLength = 250;
export const emailRegExp = /^(?=.{8,}$)(?=.*[\w])(?=.*[\W,_])(?!.*\s).*$/;
export const nameMaximumLength = 250;
